// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// .env.local を優先的に読み込む（Next.jsと同じ挙動）
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // db pull, migrate などのスキーマ操作はDirect接続（5432）を使用
    url: process.env["DIRECT_URL"],
  },
});
